from . import abstract_person
from . import hr_hospital_doctor
from . import hr_hospital_doctor_specialization
from . import hr_hospital_doctor_schedule
from . import hr_hospital_patient
from . import hr_hospital_patient_doctor_history
from . import hr_hospital_contact_person
from . import hr_hospital_disease
from . import hr_hospital_visit
from . import hr_hospital_diagnosis
